# GitLab CI Pipeline for Running Tests
stages:
  - test

variables:
  HTTP_PROXY: "http://corporate-proxy:8080"
  HTTPS_PROXY: "http://corporate-proxy:8080"
  NO_PROXY: "localhost,127.0.0.1,.internal.domain"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dhttp.proxyHost=corporate-proxy -Dhttp.proxyPort=8080 -Dhttps.proxyHost=corporate-proxy -Dhttps.proxyPort=8080"

cache:
  paths:
    - .m2/repository/

test:
  stage: test
  image: openjdk:17-jdk

  script:
    - mvn clean test

  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    paths:
      - target/surefire-reports/
    expire_in: 1 week

# Scheduled pipeline  needs to be configured in GitLab UI under CI/CD > Schedules
